PION_WORLD = "http://world.pionnet.co.kr/"
TAB_LIST = [
    "overview.html",
    "history.html",
    "business.html",
    "organization.html",
    "ceomessage.html",
    "office.html",
    "ourstory.html",
    "news.html",
    "clubs.html",
    "talk.html",
    "welfare.html",
    "framework.html",
    "oncommerce.html",
    "onmobile.html",
    "hyperspace.html",
    "dragoneye.html",
    "cloudasp.html",
    "consulting.html",
    "intergration.html",
    "management.html",
    "casestudy.html",
    "customers.html",
    "references.html",
    "recruit.html",
    "info.html",
    "location.html",
]

